version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - huggingface_cache:/root/.cache/huggingface
    environment:
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
      - HF_HOME=/root/.cache/huggingface
      - HF_DATASETS_CACHE=/root/.cache/huggingface
      - HUGGINGFACE_HUB_CACHE=/root/.cache/huggingface

volumes:
  huggingface_cache:
