version: '3.8'

services:
  article-qa:
    build: .
    image: article-qa:latest
    ports:
      - "${PORT:-8501}:8501"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_COUNT:-all}
              capabilities: [gpu]
        limits:
          memory: ${MEMORY_LIMIT:-12g}
          cpus: ${CPU_LIMIT:-2}
    environment:
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
      - HF_HOME=/root/.cache/huggingface
      - HF_DATASETS_CACHE=/root/.cache/huggingface
      - HUGGINGFACE_HUB_CACHE=/root/.cache/huggingface
      # Proxy settings
      - HTTPS_PROXY=${HTTPS_PROXY:-}
      - HTTP_PROXY=${HTTP_PROXY:-}
      - NO_PROXY=localhost,127.0.0.1
      # Application settings
      - DOWNLOAD_MODELS=${DOWNLOAD_MODELS:-true}
      - FORCE_DOWNLOAD=${FORCE_DOWNLOAD:-false}
      - DOWNLOAD_ALL_MODELS=${DOWNLOAD_ALL_MODELS:-false}
      - REQUIRE_DOWNLOADS=${REQUIRE_DOWNLOADS:-false}
      # Hardware settings
      - USE_GPU=${USE_GPU:-true}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - huggingface_cache:/root/.cache/huggingface
      - ./app:/app/app
    shm_size: ${SHM_SIZE:-2gb}
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8501/_stcore/health || exit 1
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s

volumes:
  huggingface_cache:
    name: huggingface_cache

networks:
  default:
    driver: bridge